[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "Hw56Rw8tDyiezFEsVDoDJWTMssNAMNqU1MuwNaNGk63T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/navier/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
